name: Bug report
description: Report a problem with builds or the generated image
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of the bug.
      placeholder: Tell us what you saw...
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Clone repo...
        2. Run build script...
        3. Flash image...
    validations:
      required: true

  - type: input
    id: host
    attributes:
      label: Build host
      description: OS/version where you built (e.g., Ubuntu 22.04, WSL2)
      placeholder: Ubuntu 22.04

  - type: dropdown
    id: arch
    attributes:
      label: Architecture
      options:
        - arm64
        - armhf

  - type: input
    id: release
    attributes:
      label: Raspberry Pi OS release
      placeholder: bookworm/trixie

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Paste build logs or attach files
      render: shell
