name: CI (lint & sanity)

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Workflow lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Validate workflows with actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          fail_on_error: true

  sanity:
    name: Repo sanity checks
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Show config (if present)
        run: |
          if [ -f config ]; then
            echo "---- config ----"
            sed -n '1,200p' config
          else
            echo "No top-level config file found"
          fi

      - name: Shellcheck scripts/
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandirs: "scripts"
        continue-on-error: true
